spring:
  application:
    name: lightController
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  error:
    include-message: always
